### ISSUE TITLE
SyntaxError: f-string: empty expression not allowed

### ISSUE THREAD

**Issue by bntr00t** [Z3NTL3/CloudflareIPTables#1]
Line 37

the {} can not be used there it needs something inside 
i tried to fix it with this {{}} (from https://stackoverflow.com/questions/56604560/discord-py-syntaxerror-f-string-empty-expression-not-allowed) but that that errors the iptables command
sp.run(f"sudo iptables -I INPUT -p tcp -m multiport --dports http,https -s {} -j ACCEPT".format(ipv4s),shell=True)

**Comment by Z3NTL3** [comment]
Hello,

I have resolved the issue. It would work right now.

**Comment by Z3NTL3** [comment]
Hello,

I have resolved the issue. It would work right now.

The issue reason was because you cannot do f"string" with .format()

**Comment by bntr00t** [comment]
NOOOOOOOOOOOOOOO, without f you cant use the {}

**Comment by Z3NTL3** [comment]
> NOOOOOOOOOOOOOOO, without f you cant use the {}

Literally bruh bro. I have a 5 year long experience with Python.

As it can be seen in nother tool of me

**Comment by bntr00t** [comment]
as much experience as you have, your script doesnt work on my vps

root@:~/CloudflareIPTables# python anti_ddos_cf_iptables.py
Error occured look into logs.log for details
root@:~/CloudflareIPTables#

Log
02/28/2022 12:52:11 AM Something wrong happened
02/28/2022 12:52:30 AM Something wrong happened
02/28/2022 01:57:53 AM Something wrong happened

triple quotes do not fix that issue aswell
