### ISSUE TITLE
reference to issue 1

### ISSUE THREAD

**Issue by bntr00t** [Z3NTL3/CloudflareIPTables#2]
as much experience as you have, your script doesnt work on my vps

root@:/CloudflareIPTables# python anti_ddos_cf_iptables.py
Error occured look into logs.log for details
root@:/CloudflareIPTables#

Log
02/28/2022 12:52:11 AM Something wrong happened
02/28/2022 12:52:30 AM Something wrong happened
02/28/2022 01:57:53 AM Something wrong happened

triple quotes do not fix that issue aswell

_Originally posted by @bntr00t in https://github.com/Z3NTL3/CloudflareIPTables/issues/1#issuecomment-1053730919_

**Comment by bntr00t** [comment]
![image](https://user-images.githubusercontent.com/58895443/155906003-11c8fe41-b8dd-46d3-b653-4d6f4f225b8b.png)

vps info(do i need debian for this?)

**Comment by Z3NTL3** [comment]
![image](https://user-images.githubusercontent.com/48758770/155967245-18f3cc52-77f9-40c0-9bd9-de712c58f1cf.png)
Sorry I see. There was a programming fault in my code. I solved it and tested it on my own server. It works now. 

Thanks for creating an ISSUE <3

**Comment by bntr00t** [comment]
Ah I see, I will test it on my server and keep you updated

**Comment by Z3NTL3** [comment]
> Ah I see, I will test it on my server and keep you updated

Let me know

**Comment by bntr00t** [comment]
sudo python anti_ddos_cf_iptables.py
ip6tables v1.8.4 (legacy): host/network `173.245.48.0' not found
Try `ip6tables -h' or 'ip6tables --help' for more information.
ip6tables v1.8.4 (legacy): host/network `103.21.244.0' not found
Try `ip6tables -h' or 'ip6tables --help' for more information.
ip6tables v1.8.4 (legacy): host/network `103.22.200.0' not found
Try `ip6tables -h' or 'ip6tables --help' for more information.
ip6tables v1.8.4 (legacy): host/network `103.31.4.0' not found
Try `ip6tables -h' or 'ip6tables --help' for more information.
ip6tables v1.8.4 (legacy): host/network `141.101.64.0' not found
Try `ip6tables -h' or 'ip6tables --help' for more information.
ip6tables v1.8.4 (legacy): host/network `108.162.192.0' not found
Try `ip6tables -h' or 'ip6tables --help' for more information.
ip6tables v1.8.4 (legacy): host/network `190.93.240.0' not found
Try `ip6tables -h' or 'ip6tables --help' for more information.
ip6tables v1.8.4 (legacy): host/network `188.114.96.0' not found
Try `ip6tables -h' or 'ip6tables --help' for more information.
ip6tables v1.8.4 (legacy): host/network `197.234.240.0' not found
Try `ip6tables -h' or 'ip6tables --help' for more information.
ip6tables v1.8.4 (legacy): host/network `198.41.128.0' not found
Try `ip6tables -h' or 'ip6tables --help' for more information.
ip6tables v1.8.4 (legacy): host/network `162.158.0.0' not found
Try `ip6tables -h' or 'ip6tables --help' for more information.
ip6tables v1.8.4 (legacy): host/network `104.16.0.0' not found
Try `ip6tables -h' or 'ip6tables --help' for more information.
ip6tables v1.8.4 (legacy): host/network `104.24.0.0' not found
Try `ip6tables -h' or 'ip6tables --help' for more information.
ip6tables v1.8.4 (legacy): host/network `172.64.0.0' not found
Try `ip6tables -h' or 'ip6tables --help' for more information.
ip6tables v1.8.4 (legacy): host/network `131.0.72.0' not found
Try `ip6tables -h' or 'ip6tables --help' for more information.
iptables v1.8.4 (legacy): invalid port/service `http,https' specified
Try `iptables -h' or 'iptables --help' for more information.
ip6tables v1.8.4 (legacy): invalid port/service `http,https' specified
Try `ip6tables -h' or 'ip6tables --help' for more information.
Successfully allowed ONLY CLOUDFLARE IPs REVERSE PROXY TECHNOLOGY and disallowed all requests from other.
Allowed only IP requests which came from the cloudflare cdn reverse proxy end


i guess this is just an issue with ip6 not being compatible with ipv4 ips 
but the 

iptables v1.8.4 (legacy): invalid port/service `http,https' specified
Try `iptables -h' or 'iptables --help' for more information.
ip6tables v1.8.4 (legacy): invalid port/service `http,https' specified
Try `ip6tables -h' or 'ip6tables --help' for more information.

seems like a problem

**Comment by Z3NTL3** [comment]
> sudo python anti_ddos_cf_iptables.py ip6tables v1.8.4 (legacy): host/network `173.245.48.0' not found Try `ip6tables -h' or 'ip6tables --help' for more information. ip6tables v1.8.4 (legacy): host/network `103.21.244.0' not found Try `ip6tables -h' or 'ip6tables --help' for more information. ip6tables v1.8.4 (legacy): host/network `103.22.200.0' not found Try `ip6tables -h' or 'ip6tables --help' for more information. ip6tables v1.8.4 (legacy): host/network `103.31.4.0' not found Try `ip6tables -h' or 'ip6tables --help' for more information. ip6tables v1.8.4 (legacy): host/network `141.101.64.0' not found Try `ip6tables -h' or 'ip6tables --help' for more information. ip6tables v1.8.4 (legacy): host/network `108.162.192.0' not found Try `ip6tables -h' or 'ip6tables --help' for more information. ip6tables v1.8.4 (legacy): host/network `190.93.240.0' not found Try `ip6tables -h' or 'ip6tables --help' for more information. ip6tables v1.8.4 (legacy): host/network `188.114.96.0' not found Try `ip6tables -h' or 'ip6tables --help' for more information. ip6tables v1.8.4 (legacy): host/network `197.234.240.0' not found Try `ip6tables -h' or 'ip6tables --help' for more information. ip6tables v1.8.4 (legacy): host/network `198.41.128.0' not found Try `ip6tables -h' or 'ip6tables --help' for more information. ip6tables v1.8.4 (legacy): host/network `162.158.0.0' not found Try `ip6tables -h' or 'ip6tables --help' for more information. ip6tables v1.8.4 (legacy): host/network `104.16.0.0' not found Try `ip6tables -h' or 'ip6tables --help' for more information. ip6tables v1.8.4 (legacy): host/network `104.24.0.0' not found Try `ip6tables -h' or 'ip6tables --help' for more information. ip6tables v1.8.4 (legacy): host/network `172.64.0.0' not found Try `ip6tables -h' or 'ip6tables --help' for more information. ip6tables v1.8.4 (legacy): host/network `131.0.72.0' not found Try `ip6tables -h' or 'ip6tables --help' for more information. iptables v1.8.4 (legacy): invalid port/service `http,https' specified Try `iptables -h' or 'iptables --help' for more information. ip6tables v1.8.4 (legacy): invalid port/service `http,https' specified Try `ip6tables -h' or 'ip6tables --help' for more information. Successfully allowed ONLY CLOUDFLARE IPs REVERSE PROXY TECHNOLOGY and disallowed all requests from other. Allowed only IP requests which came from the cloudflare cdn reverse proxy end
> 
> i guess this is just an issue with ip6 not being compatible with ipv4 ips but the
> 
> iptables v1.8.4 (legacy): invalid port/service `http,https' specified Try `iptables -h' or 'iptables --help' for more information. ip6tables v1.8.4 (legacy): invalid port/service `http,https' specified Try `ip6tables -h' or 'ip6tables --help' for more information.
> 
> seems like a problem

There is nothing with the program code, as it is executing the correct value and items. If you think I am wrong simply add a echo to the sp.run's and you'll see.

Even if running it without that as u can see:
![image](https://user-images.githubusercontent.com/48758770/156009879-f0d578f8-dc01-4f77-93d1-e2fdd1cd5471.png)

A solve to the problem is:
https://access.redhat.com/solutions/3138851
https://access.redhat.com/solutions/3138851

**Comment by bntr00t** [comment]
iptables v1.8.4 (legacy): invalid port/service `http,https' specified
Try `iptables -h' or 'iptables --help' for more information.
ip6tables v1.8.4 (legacy): invalid port/service `http,https' specified
Try `ip6tables -h' or 'ip6tables --help' for more information.
Successfully allowed ONLY CLOUDFLARE IPs REVERSE PROXY TECHNOLOGY and disallowed all requests from other.
Allowed only IP requests which came from the cloudflare cdn reverse proxy end

i am getting this error on my VPS, my website is online and working, the ports are opened, ssl is installed

**Comment by Z3NTL3** [comment]
We'll the code is not wrong as if you type echo on all the sp.runs you can see it is iteraing and executing the correct shit i really dont know the reason anymore it is very strange tho.

You can use this bash scripts which does literally the exact same process:
https://gist.github.com/Manouchehri/cdd4e56db6596e7c3c5a

**Comment by bntr00t** [comment]
Thank you very much, didn't know that existed aswell, will try those. Appreciate the help

**Comment by Z3NTL3** [comment]
And tbh before it had no error the http,https not specified error you was getting due i forgot to strip over the scraped elements, it has 0 bugs now fixed. + I have added a feature which automaticly sets up all for you without even logging into your machine
